@Catalog_HostAddress = https://localhost:7229/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
    "name": "mahmoud",
    "description": "A NEW swn product for outdoor enthusiasts",
    "price": 59.99,
    "imageUrl": "product10.png"
}
###

PUT {{Catalog_HostAddress}}/1
Content-Type: application/json
{    
    "name": "samsung",
    "description": "A fantastic product for outdoor enthusiasts",
    "price": 888,
    "imageUrl": "product1.png"
}

### Delete
DELETE {{Catalog_HostAddress}}/10
Content-Type: application/json



### Support AI

GET {{Catalog_HostAddress}}/support/hello
Accept: application/json


### Traditional Search

GET {{Catalog_HostAddress}}/search/samsung
Accept: application/json

### AI Search

GET {{Catalog_HostAddress}}/aisearch/Something_for_rainy_days
Accept: application/json

###