@Catalog_HostAddress = https://localhost:7229/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
    "name": "mahmoud",
    "description": "A NEW swn product for outdoor enthusiasts",
    "price": 59.99,
    "imageUrl": "product10.png"
}
###

PUT {{Catalog_HostAddress}}/5
Content-Type: application/json
{    
    "name": "IPhone",
    "description": "A fantastic product for outdoor enthusiasts",
    "price": 5.99,
    "imageUrl": "product1.png"
}

###
DELETE {{Catalog_HostAddress}}/10
Content-Type: application/json